name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.5-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: mvn clean test
